POST http://localhost:8743/v1/api/sale/save
Content-Type: application/json

{
  "productId": 2,
  "customerId": 2,
  "quantity": 20,
  "status": true
}

###

POST http://localhost:8181/ms-sale/v1/api/sale/save
Content-Type: application/json

{
  "productId": 1,
  "customerId": 2,
  "quantity": 10,
  "status": true
}

###

GET http://localhost:8743/v1/api/sale?idCustomer=2
Accept: application/json

###


GET http://localhost:8181/ms-sale/v1/api/sale?idCustomer=5
Accept: application/json

###


GET http://localhost:8743/v1/api/sale/validar
Accept: application/json

###